export interface DistrictData {
  name: string;
  cities: string[];
}

export interface LocationState {
  name: string;
  isUT?: boolean;
  languages: string[];
  districts: DistrictData[];
}

export const INDIAN_LOCATIONS: LocationState[] = [
  // 1. Andhra Pradesh (26 districts)
  {
    name: 'Andhra Pradesh',
    languages: ['Telugu', 'English', 'Hindi'],
    districts: [
      { name: 'Alluri Sitharama Raju', cities: ['Paderu', 'Araku Valley', 'Rampachodavaram'] },
      { name: 'Anakapalli', cities: ['Anakapalle', 'Chodavaram', 'Narsipatnam'] },
      { name: 'Ananthapuramu', cities: ['Anantapur', 'Dharmavaram', 'Guntakal'] },
      { name: 'Annamayya', cities: ['Rayachoti', 'Madanapalle', 'Rajampet'] },
      { name: 'Bapatla', cities: ['Bapatla', 'Chirala', 'Repalle'] },
      { name: 'Chittoor', cities: ['Chittoor', 'Palamaner', 'Nagari'] },
      { name: 'East Godavari', cities: ['Rajamahendravaram', 'Kovvur', 'Nidadavole'] },
      { name: 'Eluru', cities: ['Eluru', 'Jangareddigudem', 'Nuzvid'] },
      { name: 'Guntur', cities: ['Guntur', 'Tenali', 'Mangalagiri'] },
      { name: 'Kakinada', cities: ['Kakinada', 'Pithapuram', 'Samalkot'] },
      { name: 'Konaseema', cities: ['Amalapuram', 'Ramachandrapuram', 'Razole'] },
      { name: 'Kurnool', cities: ['Kurnool', 'Adoni', 'Yemmiganur'] },
      { name: 'Nandyal', cities: ['Nandyal', 'Dhone', 'Allagadda'] },
      { name: 'NTR', cities: ['Vijayawada', 'Jaggayyapeta', 'Nandigama'] },
      { name: 'Palnadu', cities: ['Narasaraopet', 'Gurazala', 'Sattenapalle'] },
      { name: 'Parvathipuram Manyam', cities: ['Parvathipuram', 'Salur'] },
      { name: 'Prakasam', cities: ['Ongole', 'Kandukur', 'Markapur'] },
      { name: 'Sri Potti Sriramulu Nellore', cities: ['Nellore', 'Kavali', 'Gudur'] },
      { name: 'Sri Sathya Sai', cities: ['Puttaparthi', 'Kadiri', 'Hindupur'] },
      { name: 'Srikakulam', cities: ['Srikakulam', 'Palasa', 'Amadalavalasa'] },
      { name: 'Tirupati', cities: ['Tirupati', 'Srikalahasti', 'Gudur'] },
      { name: 'Visakhapatnam', cities: ['Visakhapatnam', 'Bheemunipatnam', 'Gajuwaka'] },
      { name: 'Vizianagaram', cities: ['Vizianagaram', 'Bobbili', 'Rajam'] },
      { name: 'West Godavari', cities: ['Bhimavaram', 'Tadepalligudem', 'Narsapuram'] },
      { name: 'YSR Kadapa', cities: ['Kadapa', 'Proddatur', 'Badvel'] },
    ],
  },

  // 2. Arunachal Pradesh (26 districts)
  {
    name: 'Arunachal Pradesh',
    languages: ['English', 'Hindi', 'Nyishi'],
    districts: [
      { name: 'Anjaw', cities: ['Hawai', 'Hayuliang'] },
      { name: 'Changlang', cities: ['Changlang', 'Miao', 'Jairampur'] },
      { name: 'Dibang Valley', cities: ['Anini'] },
      { name: 'East Kameng', cities: ['Seppa'] },
      { name: 'East Siang', cities: ['Pasighat', 'Ruksin'] },
      { name: 'Itanagar Capital Complex', cities: ['Itanagar', 'Naharlagun', 'Nirjuli'] },
      { name: 'Kamle', cities: ['Raga'] },
      { name: 'Kra Daadi', cities: ['Palin'] },
      { name: 'Kurung Kumey', cities: ['Koloriang'] },
      { name: 'Lepa Rada', cities: ['Basar'] },
      { name: 'Lohit', cities: ['Tezu'] },
      { name: 'Longding', cities: ['Longding'] },
      { name: 'Lower Dibang Valley', cities: ['Roing'] },
      { name: 'Lower Subansiri', cities: ['Ziro'] },
      { name: 'Namsai', cities: ['Namsai'] },
      { name: 'Pakke Kessang', cities: ['Lemmi'] },
      { name: 'Papum Pare', cities: ['Yupia', 'Doimukh'] },
      { name: 'Shi Yomi', cities: ['Tato'] },
      { name: 'Siang', cities: ['Boleng'] },
      { name: 'Tawang', cities: ['Tawang', 'Lumla'] },
      { name: 'Tirap', cities: ['Khonsa'] },
      { name: 'Upper Siang', cities: ['Yingkiong'] },
      { name: 'Upper Subansiri', cities: ['Daporijo'] },
      { name: 'West Kameng', cities: ['Bomdila', 'Dirang'] },
      { name: 'West Siang', cities: ['Aalo'] },
    ],
  },

  // 3. Assam (31 districts)
  {
    name: 'Assam',
    languages: ['Assamese', 'English', 'Hindi', 'Bengali'],
    districts: [
      { name: 'Baksa', cities: ['Mushalpur'] },
      { name: 'Barpeta', cities: ['Barpeta', 'Howly'] },
      { name: 'Biswanath', cities: ['Biswanath Chariali'] },
      { name: 'Bongaigaon', cities: ['Bongaigaon'] },
      { name: 'Cachar', cities: ['Silchar', 'Lakhipur'] },
      { name: 'Charaideo', cities: ['Sonari'] },
      { name: 'Chirang', cities: ['Kajalgaon'] },
      { name: 'Darrang', cities: ['Mangaldoi'] },
      { name: 'Dhemaji', cities: ['Dhemaji'] },
      { name: 'Dhubri', cities: ['Dhubri', 'Gauripur'] },
      { name: 'Dibrugarh', cities: ['Dibrugarh', 'Naharkatia'] },
      { name: 'Dima Hasao', cities: ['Haflong'] },
      { name: 'Goalpara', cities: ['Goalpara'] },
      { name: 'Golaghat', cities: ['Golaghat', 'Dergaon'] },
      { name: 'Hailakandi', cities: ['Hailakandi'] },
      { name: 'Hojai', cities: ['Hojai', 'Lanka'] },
      { name: 'Jorhat', cities: ['Jorhat', 'Titabor'] },
      { name: 'Kamrup', cities: ['Amingaon', 'R Rangia'] },
      { name: 'Kamrup Metropolitan', cities: ['Guwahati', 'Dispur'] },
      { name: 'Karbi Anglong', cities: ['Diphu'] },
      { name: 'Karimganj', cities: ['Karimganj'] },
      { name: 'Kokrajhar', cities: ['Kokrajhar'] },
      { name: 'Lakhimpur', cities: ['North Lakhimpur'] },
      { name: 'Majuli', cities: ['Garamur'] },
      { name: 'Morigaon', cities: ['Morigaon'] },
      { name: 'Nagaon', cities: ['Nagaon', 'KALIABOR'] },
      { name: 'Nalbari', cities: ['Nalbari'] },
      { name: 'Sivasagar', cities: ['Sivasagar', 'Nazira'] },
      { name: 'Sonitpur', cities: ['Tezpur'] },
      { name: 'Tinsukia', cities: ['Tinsukia', 'Digboi'] },
      { name: 'Udalguri', cities: ['Udalguri'] },
    ],
  },

  // 4. Bihar (38 districts - COMPLETE OFFICIAL LIST)
  {
    name: 'Bihar',
    languages: ['Hindi', 'English', 'Maithili', 'Bhojpuri'],
    districts: [
      { name: 'Araria', cities: ['Araria', 'Forbesganj'] },
      { name: 'Arwal', cities: ['Arwal'] },
      { name: 'Aurangabad', cities: ['Aurangabad', 'Daudnagar'] },
      { name: 'Banka', cities: ['Banka', 'Amarpur'] },
      { name: 'Begusarai', cities: ['Begusarai', 'Barauni'] },
      { name: 'Bhagalpur', cities: ['Bhagalpur', 'Naugachhia', 'Sultanganj'] },
      { name: 'Bhojpur', cities: ['Arrah', 'Jagdispur'] },
      { name: 'Buxar', cities: ['Buxar', 'Dumraon'] },
      { name: 'Darbhanga', cities: ['Darbhanga', 'Benipur'] },
      { name: 'East Champaran', cities: ['Motihari', 'Raxaul', 'Areraj'] },
      { name: 'Gaya', cities: ['Gaya', 'Bodh Gaya', 'Sherghati'] },
      { name: 'Gopalganj', cities: ['Gopalganj', 'Mirganj'] },
      { name: 'Jamui', cities: ['Jamui', 'Jhajha'] },
      { name: 'Jehanabad', cities: ['Jehanabad'] },
      { name: 'Kaimur', cities: ['Bhabua', 'Mohania'] },
      { name: 'Katihar', cities: ['Katihar', 'Barsoi'] },
      { name: 'Khagaria', cities: ['Khagaria', 'Gogri Jamalpur'] },
      { name: 'Kishanganj', cities: ['Kishanganj', 'Bahadurganj'] },
      { name: 'Lakhisarai', cities: ['Lakhisarai'] },
      { name: 'Madhepura', cities: ['Madhepura', 'Uda Kishunganj'] },
      { name: 'Madhubani', cities: ['Madhubani', 'Jhanjharpur'] },
      { name: 'Munger', cities: ['Munger', 'Jamalpur'] },
      { name: 'Muzaffarpur', cities: ['Muzaffarpur', 'Kanti', 'Sakra', 'Motipur'] },
      { name: 'Nalanda', cities: ['Bihar Sharif', 'Rajgir', 'Hilsa'] },
      { name: 'Nawada', cities: ['Nawada', 'Hisua'] },
      { name: 'Patna', cities: ['Patna', 'Danapur', 'Phulwari Sharif', 'Patna City', 'Bihta'] },
      { name: 'Purnia', cities: ['Purnia', 'Kasba', 'Banmankhi'] },
      { name: 'Rohtas', cities: ['Sasaram', 'Dehri', 'Bikramganj'] },
      { name: 'Saharsa', cities: ['Saharsa', 'Simri Bakhtiyarpur'] },
      { name: 'Samastipur', cities: ['Samastipur', 'Dalsinghsarai'] },
      { name: 'Saran', cities: ['Chapra', 'Revelganj'] },
      { name: 'Sheikhpura', cities: ['Sheikhpura', 'Barbigha'] },
      { name: 'Sheohar', cities: ['Sheohar'] },
      { name: 'Sitamarhi', cities: ['Sitamarhi', 'Bairgania'] },
      { name: 'Siwan', cities: ['Siwan', 'Maharajganj'] },
      { name: 'Supaul', cities: ['Supaul', 'Birpur'] },
      { name: 'Vaishali', cities: ['Hajipur', 'Lalganj', 'Mahnar'] },
      { name: 'West Champaran', cities: ['Bettiah', 'Bagaha', 'Narkatiaganj'] },
    ],
  },

  // 5. Chhattisgarh (33 districts)
  {
    name: 'Chhattisgarh',
    languages: ['Hindi', 'Chhattisgarhi', 'English'],
    districts: [
      { name: 'Balod', cities: ['Balod'] },
      { name: 'Baloda Bazar', cities: ['Baloda Bazar'] },
      { name: 'Balrampur', cities: ['Balrampur'] },
      { name: 'Bastar', cities: ['Jagdalpur'] },
      { name: 'Bemetara', cities: ['Bemetara'] },
      { name: 'Bijapur', cities: ['Bijapur'] },
      { name: 'Bilaspur', cities: ['Bilaspur', 'Kota'] },
      { name: 'Dantewada', cities: ['Dantewada'] },
      { name: 'Dhamtari', cities: ['Dhamtari'] },
      { name: 'Durg', cities: ['Bhilai', 'Durg'] },
      { name: 'Gariaband', cities: ['Gariaband'] },
      { name: 'Gaurela Pendra Marwahi', cities: ['Pendra'] },
      { name: 'Janjgir-Champa', cities: ['Janjgir', 'Champa'] },
      { name: 'Jashpur', cities: ['Jashpur Nagar'] },
      { name: 'Kabirdham', cities: ['Kawardha'] },
      { name: 'Kanker', cities: ['Kanker'] },
      { name: 'Khairagarh', cities: ['Khairagarh'] },
      { name: 'Kondagaon', cities: ['Kondagaon'] },
      { name: 'Korba', cities: ['Korba', 'Katghora'] },
      { name: 'Koriya', cities: ['Baikunthpur'] },
      { name: 'Mahasamund', cities: ['Mahasamund'] },
      { name: 'Manendragarh', cities: ['Manendragarh'] },
      { name: 'Mohla Manpur', cities: ['Mohla'] },
      { name: 'Mungeli', cities: ['Mungeli'] },
      { name: 'Narayanpur', cities: ['Narayanpur'] },
      { name: 'Raigarh', cities: ['Raigarh'] },
      { name: 'Raipur', cities: ['Raipur', 'Naya Raipur', 'Abhanpur'] },
      { name: 'Rajnandgaon', cities: ['Rajnandgaon'] },
      { name: 'Sarangarh', cities: ['Sarangarh'] },
      { name: 'Sukma', cities: ['Sukma'] },
      { name: 'Surajpur', cities: ['Surajpur'] },
      { name: 'Surguja', cities: ['Ambikapur'] },
    ],
  },

  // 6. Goa (2 districts)
  {
    name: 'Goa',
    languages: ['Konkani', 'Marathi', 'Hindi', 'English'],
    districts: [
      { name: 'North Goa', cities: ['Panaji', 'Mapusa', 'Bicholim', 'Ponda'] },
      { name: 'South Goa', cities: ['Margao', 'Vasco da Gama', 'Quepem', 'Curchorem'] },
    ],
  },

  // 7. Gujarat (33 districts)
  {
    name: 'Gujarat',
    languages: ['Gujarati', 'Hindi', 'English'],
    districts: [
      { name: 'Ahmedabad', cities: ['Ahmedabad', 'Sanand', 'Dholka', 'Bavla'] },
      { name: 'Amreli', cities: ['Amreli'] },
      { name: 'Anand', cities: ['Anand', 'Khambhat'] },
      { name: 'Aravalli', cities: ['Modasa'] },
      { name: 'Banaskantha', cities: ['Palanpur', 'Desa'] },
      { name: 'Bharuch', cities: ['Bharuch', 'Ankleshwar'] },
      { name: 'Bhavnagar', cities: ['Bhavnagar'] },
      { name: 'Botad', cities: ['Botad'] },
      { name: 'Chhota Udepur', cities: ['Chhota Udepur'] },
      { name: 'Dahod', cities: ['Dahod'] },
      { name: 'Dang', cities: ['Ahwa'] },
      { name: 'Devbhumi Dwarka', cities: ['Dwarka', 'Khambhalia'] },
      { name: 'Gandhinagar', cities: ['Gandhinagar', 'Kalol'] },
      { name: 'Gir Somnath', cities: ['Veraval'] },
      { name: 'Jamnagar', cities: ['Jamnagar'] },
      { name: 'Junagadh', cities: ['Junagadh'] },
      { name: 'Kheda', cities: ['Nadiad'] },
      { name: 'Kutch', cities: ['Bhuj', 'Gandhidham'] },
      { name: 'Mahisagar', cities: ['Lunawada'] },
      { name: 'Mehsana', cities: ['Mehsana', 'Unjha'] },
      { name: 'Narmada', cities: ['Rajpipla'] },
      { name: 'Navsari', cities: ['Navsari'] },
      { name: 'Panchmahal', cities: ['Godhra'] },
      { name: 'Patan', cities: ['Patan'] },
      { name: 'Porbandar', cities: ['Porbandar'] },
      { name: 'Rajkot', cities: ['Rajkot', 'Gondal'] },
      { name: 'Sabarkantha', cities: ['Himatnagar'] },
      { name: 'Surat', cities: ['Surat', 'Kamrej', 'Bardoli'] },
      { name: 'Surendranagar', cities: ['Surendranagar'] },
      { name: 'Tapi', cities: ['Vyara'] },
      { name: 'Vadodara', cities: ['Vadodara', 'Padra'] },
      { name: 'Valsad', cities: ['Valsad', 'Vapi'] },
    ],
  },

  // 8. Haryana (22 districts)
  {
    name: 'Haryana',
    languages: ['Hindi', 'English', 'Punjabi'],
    districts: [
      { name: 'Ambala', cities: ['Ambala Cantt', 'Ambala City'] },
      { name: 'Bhiwani', cities: ['Bhiwani'] },
      { name: 'Charkhi Dadri', cities: ['Charkhi Dadri'] },
      { name: 'Faridabad', cities: ['Faridabad', 'Ballabgarh'] },
      { name: 'Fatehabad', cities: ['Fatehabad'] },
      { name: 'Gurugram', cities: ['Gurugram', 'Manesar', 'Sohna'] },
      { name: 'Hisar', cities: ['Hisar', 'Hansi'] },
      { name: 'Jhajjar', cities: ['Jhajjar', 'Bahadurgarh'] },
      { name: 'Jind', cities: ['Jind'] },
      { name: 'Kaithal', cities: ['Kaithal'] },
      { name: 'Karnal', cities: ['Karnal'] },
      { name: 'Kurukshetra', cities: ['Kurukshetra', 'Thanesar'] },
      { name: 'Mahendragarh', cities: ['Narnaul'] },
      { name: 'Nuh', cities: ['Nuh'] },
      { name: 'Palwal', cities: ['Palwal'] },
      { name: 'Panchkula', cities: ['Panchkula', 'Kalka'] },
      { name: 'Panipat', cities: ['Panipat'] },
      { name: 'Rewari', cities: ['Rewari'] },
      { name: 'Rohtak', cities: ['Rohtak'] },
      { name: 'Sirsa', cities: ['Sirsa'] },
      { name: 'Sonipat', cities: ['Sonipat'] },
      { name: 'Yamunanagar', cities: ['Yamunanagar', 'Jagadhri'] },
    ],
  },

  // 9. Himachal Pradesh (12 districts)
  {
    name: 'Himachal Pradesh',
    languages: ['Hindi', 'English', 'Pahari'],
    districts: [
      { name: 'Bilaspur', cities: ['Bilaspur'] },
      { name: 'Chamba', cities: ['Chamba', 'Dalhousie'] },
      { name: 'Hamirpur', cities: ['Hamirpur'] },
      { name: 'Kangra', cities: ['Dharamshala', 'Palampur', 'Kangra'] },
      { name: 'Kinnaur', cities: ['Reckong Peo'] },
      { name: 'Kullu', cities: ['Kullu', 'Manali'] },
      { name: 'Lahaul and Spiti', cities: ['Keylong'] },
      { name: 'Mandi', cities: ['Mandi', 'Sundernagar'] },
      { name: 'Shimla', cities: ['Shimla', 'Rampur', 'Rohru'] },
      { name: 'Sirmaur', cities: ['Nahan'] },
      { name: 'Solan', cities: ['Solan', 'Baddi'] },
      { name: 'Una', cities: ['Una'] },
    ],
  },

  // 10. Jharkhand (24 districts)
  {
    name: 'Jharkhand',
    languages: ['Hindi', 'English', 'Santhali'],
    districts: [
      { name: 'Bokaro', cities: ['Bokaro Steel City'] },
      { name: 'Chatra', cities: ['Chatra'] },
      { name: 'Deoghar', cities: ['Deoghar'] },
      { name: 'Dhanbad', cities: ['Dhanbad', 'Jharia'] },
      { name: 'Dumka', cities: ['Dumka'] },
      { name: 'East Singhbhum', cities: ['Jamshedpur', 'Ghatshila'] },
      { name: 'Garhwa', cities: ['Garhwa'] },
      { name: 'Giridih', cities: ['Giridih'] },
      { name: 'Godda', cities: ['Godda'] },
      { name: 'Gumla', cities: ['Gumla'] },
      { name: 'Hazaribagh', cities: ['Hazaribagh'] },
      { name: 'Jamtara', cities: ['Jamtara'] },
      { name: 'Khunti', cities: ['Khunti'] },
      { name: 'Koderma', cities: ['Koderma'] },
      { name: 'Latehar', cities: ['Latehar'] },
      { name: 'Lohardaga', cities: ['Lohardaga'] },
      { name: 'Pakur', cities: ['Pakur'] },
      { name: 'Palamu', cities: ['Medininagar'] },
      { name: 'Ramgarh', cities: ['Ramgarh Cantonment'] },
      { name: 'Ranchi', cities: ['Ranchi', 'Kanke', 'Hatia'] },
      { name: 'Sahibganj', cities: ['Sahibganj'] },
      { name: 'Seraikela Kharsawan', cities: ['Seraikela'] },
      { name: 'Simdega', cities: ['Simdega'] },
      { name: 'West Singhbhum', cities: ['Chaibasa'] },
    ],
  },

  // 11. Karnataka (31 districts)
  {
    name: 'Karnataka',
    languages: ['Kannada', 'English', 'Hindi', 'Telugu'],
    districts: [
      { name: 'Bagalkote', cities: ['Bagalkote'] },
      { name: 'Ballari', cities: ['Ballari'] },
      { name: 'Belagavi', cities: ['Belagavi', 'Gokak'] },
      { name: 'Bengaluru Rural', cities: ['Dharmapuri', 'Nelamangala'] },
      { name: 'Bengaluru Urban', cities: ['Bengaluru', 'Whitefield', 'Electronic City', 'Yelahanka'] },
      { name: 'Bidar', cities: ['Bidar'] },
      { name: 'Chamarajanagara', cities: ['Chamarajanagara'] },
      { name: 'Chikkaballapura', cities: ['Chikkaballapura'] },
      { name: 'Chikkamagaluru', cities: ['Chikkamagaluru'] },
      { name: 'Chitradurga', cities: ['Chitradurga'] },
      { name: 'Dakshina Kannada', cities: ['Mangaluru', 'Puttur'] },
      { name: 'Davanagere', cities: ['Davanagere'] },
      { name: 'Dharwad', cities: ['Hubballi', 'Dharwad'] },
      { name: 'Gadag', cities: ['Gadag'] },
      { name: 'Hassan', cities: ['Hassan'] },
      { name: 'Haveri', cities: ['Haveri'] },
      { name: 'Kalaburagi', cities: ['Kalaburagi'] },
      { name: 'Kodagu', cities: ['Madikeri'] },
      { name: 'Kolar', cities: ['Kolar'] },
      { name: 'Koppal', cities: ['Koppal'] },
      { name: 'Mandya', cities: ['Mandya'] },
      { name: 'Mysuru', cities: ['Mysuru', 'Nanjangud'] },
      { name: 'Raichur', cities: ['Raichur'] },
      { name: 'Ramanagara', cities: ['Ramanagara'] },
      { name: 'Shivamogga', cities: ['Shivamogga'] },
      { name: 'Tumakuru', cities: ['Tumakuru'] },
      { name: 'Udupi', cities: ['Udupi', 'Manipal'] },
      { name: 'Uttara Kannada', cities: ['Karwar'] },
      { name: 'Vijayanagara', cities: ['Hosapete'] },
      { name: 'Vijayapura', cities: ['Vijayapura'] },
      { name: 'Yadgir', cities: ['Yadgir'] },
    ],
  },

  // 12. Kerala (14 districts)
  {
    name: 'Kerala',
    languages: ['Malayalam', 'English', 'Hindi'],
    districts: [
      { name: 'Alappuzha', cities: ['Alappuzha'] },
      { name: 'Ernakulam', cities: ['Kochi', 'Aluva', 'Angamaly'] },
      { name: 'Idukki', cities: ['Thodupuzha'] },
      { name: 'Kannur', cities: ['Kannur'] },
      { name: 'Kasaragod', cities: ['Kasaragod'] },
      { name: 'Kollam', cities: ['Kollam'] },
      { name: 'Kottayam', cities: ['Kottayam'] },
      { name: 'Kozhikode', cities: ['Kozhikode', 'Vatakara'] },
      { name: 'Malappuram', cities: ['Malappuram', 'Manjeri'] },
      { name: 'Palakkad', cities: ['Palakkad'] },
      { name: 'Pathanamthitta', cities: ['Pathanamthitta'] },
      { name: 'Thiruvananthapuram', cities: ['Thiruvananthapuram', 'Neyyattinkara'] },
      { name: 'Thrissur', cities: ['Thrissur', 'Chalakudy'] },
      { name: 'Wayanad', cities: ['Kalpetta'] },
    ],
  },

  // 13. Madhya Pradesh (55 districts)
  {
    name: 'Madhya Pradesh',
    languages: ['Hindi', 'English'],
    districts: [
      { name: 'Agar Malwa', cities: ['Agar'] },
      { name: 'Alirajpur', cities: ['Alirajpur'] },
      { name: 'Anuppur', cities: ['Anuppur'] },
      { name: 'Ashoknagar', cities: ['Ashoknagar'] },
      { name: 'Balaghat', cities: ['Balaghat'] },
      { name: 'Barwani', cities: ['Barwani'] },
      { name: 'Betul', cities: ['Betul'] },
      { name: 'Bhind', cities: ['Bhind'] },
      { name: 'Bhopal', cities: ['Bhopal', 'Bairagarh'] },
      { name: 'Burhanpur', cities: ['Burhanpur'] },
      { name: 'Chhatarpur', cities: ['Chhatarpur'] },
      { name: 'Chhindwara', cities: ['Chhindwara'] },
      { name: 'Damoh', cities: ['Damoh'] },
      { name: 'Datia', cities: ['Datia'] },
      { name: 'Dewas', cities: ['Dewas'] },
      { name: 'Dhar', cities: ['Dhar'] },
      { name: 'Dindori', cities: ['Dindori'] },
      { name: 'Guna', cities: ['Guna'] },
      { name: 'Gwalior', cities: ['Gwalior', 'Dabra'] },
      { name: 'Harda', cities: ['Harda'] },
      { name: 'Indore', cities: ['Indore', 'Mhow'] },
      { name: 'Jabalpur', cities: ['Jabalpur', 'Sihora'] },
      { name: 'Jhabua', cities: ['Jhabua'] },
      { name: 'Katni', cities: ['Katni'] },
      { name: 'Khandwa', cities: ['Khandwa'] },
      { name: 'Khargone', cities: ['Khargone'] },
      { name: 'Mandla', cities: ['Mandla'] },
      { name: 'Mandsaur', cities: ['Mandsaur'] },
      { name: 'Morena', cities: ['Morena'] },
      { name: 'Narsinghpur', cities: ['Narsinghpur'] },
      { name: 'Neemuch', cities: ['Neemuch'] },
      { name: 'Niwari', cities: ['Orchha'] },
      { name: 'Panna', cities: ['Panna'] },
      { name: 'Raisen', cities: ['Raisen'] },
      { name: 'Rajgarh', cities: ['Rajgarh'] },
      { name: 'Ratlam', cities: ['Ratlam'] },
      { name: 'Rewa', cities: ['Rewa'] },
      { name: 'Sagar', cities: ['Sagar'] },
      { name: 'Satna', cities: ['Satna'] },
      { name: 'Sehore', cities: ['Sehore'] },
      { name: 'Seoni', cities: ['Seoni'] },
      { name: 'Shahdol', cities: ['Shahdol'] },
      { name: 'Shajapur', cities: ['Shajapur'] },
      { name: 'Sheopur', cities: ['Sheopur'] },
      { name: 'Shivpuri', cities: ['Shivpuri'] },
      { name: 'Sidhi', cities: ['Sidhi'] },
      { name: 'Singrauli', cities: ['Singrauli'] },
      { name: 'Tikamgarh', cities: ['Tikamgarh'] },
      { name: 'Ujjain', cities: ['Ujjain'] },
      { name: 'Umaria', cities: ['Umaria'] },
      { name: 'Vidisha', cities: ['Vidisha'] },
      { name: 'Narmadapuram', cities: ['Hoshangabad'] },
      { name: 'Mauganj', cities: ['Mauganj'] },
      { name: 'Maihar', cities: ['Maihar'] },
      { name: 'Pandhurna', cities: ['Pandhurna'] },
    ],
  },

  // 14. Maharashtra (36 districts - COMPLETE OFFICIAL LIST)
  {
    name: 'Maharashtra',
    languages: ['Marathi', 'Hindi', 'English'],
    districts: [
      { name: 'Ahmednagar', cities: ['Ahmednagar', 'Shirdi', 'Rahuri'] },
      { name: 'Akola', cities: ['Akola', 'Akot'] },
      { name: 'Amravati', cities: ['Amravati', 'Achalpur'] },
      { name: 'Chhatrapati Sambhajinagar', cities: ['Aurangabad', 'Paithan'] },
      { name: 'Beed', cities: ['Beed', 'Parli'] },
      { name: 'Bhandara', cities: ['Bhandara'] },
      { name: 'Buldhana', cities: ['Buldhana', 'Khamgaon'] },
      { name: 'Chandrapur', cities: ['Chandrapur', 'Ballarpur'] },
      { name: 'Dhule', cities: ['Dhule', 'Shirpur'] },
      { name: 'Gadchiroli', cities: ['Gadchiroli'] },
      { name: 'Gondia', cities: ['Gondia'] },
      { name: 'Hingoli', cities: ['Hingoli'] },
      { name: 'Jalgaon', cities: ['Jalgaon', 'Bhusawal'] },
      { name: 'Jalna', cities: ['Jalna'] },
      { name: 'Kolhapur', cities: ['Kolhapur', 'Ichalkaranji'] },
      { name: 'Latur', cities: ['Latur', 'Udgir'] },
      { name: 'Mumbai City', cities: ['Mumbai', 'Colaba', 'Dadar'] },
      { name: 'Mumbai Suburban', cities: ['Bandra', 'Andheri', 'Borivali', 'Thane'] },
      { name: 'Nagpur', cities: ['Nagpur', 'Kamptee'] },
      { name: 'Nanded', cities: ['Nanded'] },
      { name: 'Nandurbar', cities: ['Nandurbar'] },
      { name: 'Nashik', cities: ['Nashik', 'Malegaon'] },
      { name: 'Dharashiv', cities: ['Osmanabad'] },
      { name: 'Palghar', cities: ['Palghar', 'Vasai-Virar'] },
      { name: 'Parbhani', cities: ['Parbhani'] },
      { name: 'Pune', cities: ['Pune', 'Pimpri-Chinchwad', 'Baramati'] },
      { name: 'Raigad', cities: ['Panvel', 'Alibag'] },
      { name: 'Ratnagiri', cities: ['Ratnagiri', 'Chiplun'] },
      { name: 'Sangli', cities: ['Sangli', 'Miraj'] },
      { name: 'Satara', cities: ['Satara', 'Karad'] },
      { name: 'Sindhudurg', cities: ['Kudal', 'Sawantwadi'] },
      { name: 'Solapur', cities: ['Solapur', 'Pandharpur'] },
      { name: 'Thane', cities: ['Thane', 'Kalyan', 'Dombivli'] },
      { name: 'Wardha', cities: ['Wardha'] },
      { name: 'Washim', cities: ['Washim'] },
      { name: 'Yavatmal', cities: ['Yavatmal'] },
    ],
  },

  // 15. Manipur (16 districts)
  {
    name: 'Manipur',
    languages: ['Manipuri', 'English', 'Hindi'],
    districts: [
      { name: 'Bishnupur', cities: ['Bishnupur'] },
      { name: 'Chandel', cities: ['Chandel'] },
      { name: 'Churachandpur', cities: ['Churachandpur'] },
      { name: 'Imphal East', cities: ['Porompat'] },
      { name: 'Imphal West', cities: ['Imphal', 'Lamphelpat'] },
      { name: 'Jiribam', cities: ['Jiribam'] },
      { name: 'Kakching', cities: ['Kakching'] },
      { name: 'Kamjong', cities: ['Kamjong'] },
      { name: 'Kangpokpi', cities: ['Kangpokpi'] },
      { name: 'Noney', cities: ['Noney'] },
      { name: 'Pherzawl', cities: ['Pherzawl'] },
      { name: 'Senapati', cities: ['Senapati'] },
      { name: 'Tamenglong', cities: ['Tamenglong'] },
      { name: 'Tengnoupal', cities: ['Tengnoupal'] },
      { name: 'Thoubal', cities: ['Thoubal'] },
      { name: 'Ukhrul', cities: ['Ukhrul'] },
    ],
  },

  // 16. Meghalaya (12 districts)
  {
    name: 'Meghalaya',
    languages: ['English', 'Khasi', 'Garo', 'Hindi'],
    districts: [
      { name: 'East Garo Hills', cities: ['Williamnagar'] },
      { name: 'East Jaintia Hills', cities: ['Khliehriat'] },
      { name: 'East Khasi Hills', cities: ['Shillong', 'Sohra'] },
      { name: 'Eastern West Khasi Hills', cities: ['Mairang'] },
      { name: 'North Garo Hills', cities: ['Resubelpara'] },
      { name: 'Ri Bhoi', cities: ['Nongpoh'] },
      { name: 'South Garo Hills', cities: ['Baghmara'] },
      { name: 'South West Garo Hills', cities: ['Ampati'] },
      { name: 'South West Khasi Hills', cities: ['Mawkyrwat'] },
      { name: 'West Garo Hills', cities: ['Tura'] },
      { name: 'West Jaintia Hills', cities: ['Jowai'] },
      { name: 'West Khasi Hills', cities: ['Nongstoin'] },
    ],
  },

  // 17. Mizoram (11 districts)
  {
    name: 'Mizoram',
    languages: ['Mizo', 'English', 'Hindi'],
    districts: [
      { name: 'Aizawl', cities: ['Aizawl', 'Darlawn'] },
      { name: 'Champhai', cities: ['Champhai'] },
      { name: 'Hnahthial', cities: ['Hnahthial'] },
      { name: 'Khawzawl', cities: ['Khawzawl'] },
      { name: 'Kolasib', cities: ['Kolasib'] },
      { name: 'Lawngtlai', cities: ['Lawngtlai'] },
      { name: 'Lunglei', cities: ['Lunglei'] },
      { name: 'Mamit', cities: ['Mamit'] },
      { name: 'Saitual', cities: ['Saitual'] },
      { name: 'Serchhip', cities: ['Serchhip'] },
      { name: 'Siaha', cities: ['Siaha'] },
    ],
  },

  // 18. Nagaland (16 districts)
  {
    name: 'Nagaland',
    languages: ['English', 'Hindi', 'Nagamese'],
    districts: [
      { name: 'Chumoukedima', cities: ['Chumoukedima'] },
      { name: 'Dimapur', cities: ['Dimapur'] },
      { name: 'Kiphire', cities: ['Kiphire'] },
      { name: 'Kohima', cities: ['Kohima', 'Tseminyu'] },
      { name: 'Longleng', cities: ['Longleng'] },
      { name: 'Mokokchung', cities: ['Mokokchung'] },
      { name: 'Mon', cities: ['Mon'] },
      { name: 'Niuland', cities: ['Niuland'] },
      { name: 'Noklak', cities: ['Noklak'] },
      { name: 'Peren', cities: ['Peren'] },
      { name: 'Phek', cities: ['Phek'] },
      { name: 'Shamator', cities: ['Shamator'] },
      { name: 'Tseminyu', cities: ['Tseminyu'] },
      { name: 'Tuensang', cities: ['Tuensang'] },
      { name: 'Wokha', cities: ['Wokha'] },
      { name: 'Zunheboto', cities: ['Zunheboto'] },
    ],
  },

  // 19. Odisha (30 districts)
  {
    name: 'Odisha',
    languages: ['Odia', 'English', 'Hindi'],
    districts: [
      { name: 'Angul', cities: ['Angul'] },
      { name: 'Balangir', cities: ['Balangir'] },
      { name: 'Balasore', cities: ['Balasore'] },
      { name: 'Bargarh', cities: ['Bargarh'] },
      { name: 'Bhadrak', cities: ['Bhadrak'] },
      { name: 'Boudh', cities: ['Boudh'] },
      { name: 'Cuttack', cities: ['Cuttack', 'Choudwar'] },
      { name: 'Deogarh', cities: ['Deogarh'] },
      { name: 'Dhenkanal', cities: ['Dhenkanal'] },
      { name: 'Gajapati', cities: ['Paralakhemundi'] },
      { name: 'Ganjam', cities: ['Berhampur', 'Chhatrapur'] },
      { name: 'Jagatsinghpur', cities: ['Jagatsinghpur'] },
      { name: 'Jajpur', cities: ['Jajpur'] },
      { name: 'Jharsuguda', cities: ['Jharsuguda'] },
      { name: 'Kalahandi', cities: ['Bhawanipatna'] },
      { name: 'Kandhamal', cities: ['Phulbani'] },
      { name: 'Kendrapara', cities: ['Kendrapara'] },
      { name: 'Keonjhar', cities: ['Kendujhar'] },
      { name: 'Khordha', cities: ['Bhubaneswar', 'Jatni'] },
      { name: 'Koraput', cities: ['Koraput', 'Jeypore'] },
      { name: 'Malkangiri', cities: ['Malkangiri'] },
      { name: 'Mayurbhanj', cities: ['Baripada'] },
      { name: 'Nabarangpur', cities: ['Nabarangpur'] },
      { name: 'Nayagarh', cities: ['Nayagarh'] },
      { name: 'Nuapada', cities: ['Nuapada'] },
      { name: 'Puri', cities: ['Puri'] },
      { name: 'Rayagada', cities: ['Rayagada'] },
      { name: 'Sambalpur', cities: ['Sambalpur'] },
      { name: 'Sonepur', cities: ['Subarnapur'] },
      { name: 'Sundargarh', cities: ['Rourkela', 'Sundargarh'] },
    ],
  },

  // 20. Punjab (23 districts)
  {
    name: 'Punjab',
    languages: ['Punjabi', 'Hindi', 'English'],
    districts: [
      { name: 'Amritsar', cities: ['Amritsar', 'Attari'] },
      { name: 'Barnala', cities: ['Barnala'] },
      { name: 'Bathinda', cities: ['Bathinda'] },
      { name: 'Faridkot', cities: ['Faridkot'] },
      { name: 'Fatehgarh Sahib', cities: ['Sirhind'] },
      { name: 'Fazilka', cities: ['Fazilka', 'Abohar'] },
      { name: 'Firozpur', cities: ['Firozpur'] },
      { name: 'Gurdaspur', cities: ['Gurdaspur', 'Batala'] },
      { name: 'Hoshiarpur', cities: ['Hoshiarpur'] },
      { name: 'Jalandhar', cities: ['Jalandhar', 'Phagwara'] },
      { name: 'Kapurthala', cities: ['Kapurthala'] },
      { name: 'Ludhiana', cities: ['Ludhiana', 'Khanna'] },
      { name: 'Malerkotla', cities: ['Malerkotla'] },
      { name: 'Mansa', cities: ['Mansa'] },
      { name: 'Moga', cities: ['Moga'] },
      { name: 'Pathankot', cities: ['Pathankot'] },
      { name: 'Patiala', cities: ['Patiala', 'Rajpura'] },
      { name: 'Rupnagar', cities: ['Ropar'] },
      { name: 'Sahibzada Ajit Singh Nagar', cities: ['Mohali', 'Kharar'] },
      { name: 'Sangrur', cities: ['Sangrur'] },
      { name: 'Shahid Bhagat Singh Nagar', cities: ['Nawanshahr'] },
      { name: 'Sri Muktsar Sahib', cities: ['Muktsar'] },
      { name: 'Tarn Taran', cities: ['Tarn Taran Sahib'] },
    ],
  },

  // 21. Rajasthan (50 districts)
  {
    name: 'Rajasthan',
    languages: ['Hindi', 'English', 'Rajasthani'],
    districts: [
      { name: 'Ajmer', cities: ['Ajmer', 'Beawar'] },
      { name: 'Alwar', cities: ['Alwar', 'Bhiwadi'] },
      { name: 'Anupgarh', cities: ['Anupgarh'] },
      { name: 'Balotra', cities: ['Balotra'] },
      { name: 'Banswara', cities: ['Banswara'] },
      { name: 'Baran', cities: ['Baran'] },
      { name: 'Barmer', cities: ['Barmer'] },
      { name: 'Beawar', cities: ['Beawar'] },
      { name: 'Bharatpur', cities: ['Bharatpur'] },
      { name: 'Bhilwara', cities: ['Bhilwara'] },
      { name: 'Bikaner', cities: ['Bikaner'] },
      { name: 'Bundi', cities: ['Bundi'] },
      { name: 'Chittorgarh', cities: ['Chittorgarh'] },
      { name: 'Churu', cities: ['Churu'] },
      { name: 'Dausa', cities: ['Dausa'] },
      { name: 'Deeg', cities: ['Deeg'] },
      { name: 'Dholpur', cities: ['Dholpur'] },
      { name: 'Didwana Kuchaman', cities: ['Didwana'] },
      { name: 'Dudu', cities: ['Dudu'] },
      { name: 'Dungarpur', cities: ['Dungarpur'] },
      { name: 'Ganganagar', cities: ['Sri Ganganagar'] },
      { name: 'Gangapur City', cities: ['Gangapur'] },
      { name: 'Hanumangarh', cities: ['Hanumangarh'] },
      { name: 'Jaipur', cities: ['Jaipur', 'Sanganer', 'Amer'] },
      { name: 'Jaipur Gramin', cities: ['Chomu'] },
      { name: 'Jaisalmer', cities: ['Jaisalmer'] },
      { name: 'Jalore', cities: ['Jalore'] },
      { name: 'Jhalawar', cities: ['Jhalawar'] },
      { name: 'Jhunjhunu', cities: ['Jhunjhunu'] },
      { name: 'Jodhpur', cities: ['Jodhpur', 'Luni'] },
      { name: 'Jodhpur Gramin', cities: ['Osian'] },
      { name: 'Karauli', cities: ['Karauli'] },
      { name: 'Kekri', cities: ['Kekri'] },
      { name: 'Kota', cities: ['Kota', 'Ramganj Mandi'] },
      { name: 'Kotputli Behror', cities: ['Kotputli'] },
      { name: 'Khairthal Tijara', cities: ['Tijara'] },
      { name: 'Nagaur', cities: ['Nagaur'] },
      { name: 'Neem Ka Thana', cities: ['Neem Ka Thana'] },
      { name: 'Pali', cities: ['Pali'] },
      { name: 'Phalodi', cities: ['Phalodi'] },
      { name: 'Pratapgarh', cities: ['Pratapgarh'] },
      { name: 'Rajsamand', cities: ['Rajsamand'] },
      { name: 'Salumbar', cities: ['Salumbar'] },
      { name: 'Sanchore', cities: ['Sanchore'] },
      { name: 'Sawai Madhopur', cities: ['Sawai Madhopur'] },
      { name: 'Shahpura', cities: ['Shahpura'] },
      { name: 'Sikar', cities: ['Sikar'] },
      { name: 'Sirohi', cities: ['Sirohi', 'Mount Abu'] },
      { name: 'Tonk', cities: ['Tonk'] },
      { name: 'Udaipur', cities: ['Udaipur', 'Fatehnagar'] },
    ],
  },

  // 22. Sikkim (6 districts)
  {
    name: 'Sikkim',
    languages: ['Nepali', 'English', 'Hindi', 'Sikkimese'],
    districts: [
      { name: 'Gangtok', cities: ['Gangtok', 'Singtam'] },
      { name: 'Gyalshing', cities: ['Gyalshing'] },
      { name: 'Mangan', cities: ['Mangan'] },
      { name: 'Namchi', cities: ['Namchi', 'Jorethang'] },
      { name: 'Pakyong', cities: ['Pakyong'] },
      { name: 'Soreng', cities: ['Soreng'] },
    ],
  },

  // 23. Tamil Nadu (38 districts)
  {
    name: 'Tamil Nadu',
    languages: ['Tamil', 'English', 'Hindi'],
    districts: [
      { name: 'Ariyalur', cities: ['Ariyalur'] },
      { name: 'Chengalpattu', cities: ['Chengalpattu', 'Tambaram'] },
      { name: 'Chennai', cities: ['Chennai', 'Adyar', 'T. Nagar', 'Anna Nagar'] },
      { name: 'Coimbatore', cities: ['Coimbatore', 'Pollachi'] },
      { name: 'Cuddalore', cities: ['Cuddalore'] },
      { name: 'Dharmapuri', cities: ['Dharmapuri'] },
      { name: 'Dindigul', cities: ['Dindigul'] },
      { name: 'Erode', cities: ['Erode'] },
      { name: 'Kallakurichi', cities: ['Kallakurichi'] },
      { name: 'Kanchipuram', cities: ['Kanchipuram'] },
      { name: 'Kanyakumari', cities: ['Nagercoil'] },
      { name: 'Karur', cities: ['Karur'] },
      { name: 'Krishnagiri', cities: ['Hosur', 'Krishnagiri'] },
      { name: 'Madurai', cities: ['Madurai', 'Melur'] },
      { name: 'Mayiladuthurai', cities: ['Mayiladuthurai'] },
      { name: 'Nagapattinam', cities: ['Nagapattinam'] },
      { name: 'Namakkal', cities: ['Namakkal'] },
      { name: 'Nilgiris', cities: ['Udhagamandalam (Ooty)'] },
      { name: 'Perambalur', cities: ['Perambalur'] },
      { name: 'Pudukkottai', cities: ['Pudukkottai'] },
      { name: 'Ramanathapuram', cities: ['Ramanathapuram'] },
      { name: 'Ranipet', cities: ['Ranipet'] },
      { name: 'Salem', cities: ['Salem'] },
      { name: 'Sivaganga', cities: ['Sivaganga'] },
      { name: 'Tenkasi', cities: ['Tenkasi'] },
      { name: 'Thanjavur', cities: ['Thanjavur'] },
      { name: 'Theni', cities: ['Theni'] },
      { name: 'Thoothukudi', cities: ['Thoothukudi'] },
      { name: 'Tiruchirappalli', cities: ['Tiruchirappalli', 'Srirangam'] },
      { name: 'Tirunelveli', cities: ['Tirunelveli'] },
      { name: 'Tirupathur', cities: ['Tirupathur'] },
      { name: 'Tiruppur', cities: ['Tiruppur'] },
      { name: 'Tiruvallur', cities: ['Tiruvallur', 'Avadi'] },
      { name: 'Tiruvannamalai', cities: ['Tiruvannamalai'] },
      { name: 'Tiruvarur', cities: ['Tiruvarur'] },
      { name: 'Vellore', cities: ['Vellore'] },
      { name: 'Viluppuram', cities: ['Viluppuram'] },
      { name: 'Virudhunagar', cities: ['Virudhunagar', 'Sivakasi'] },
    ],
  },

  // 24. Telangana (33 districts)
  {
    name: 'Telangana',
    languages: ['Telugu', 'English', 'Hindi', 'Urdu'],
    districts: [
      { name: 'Adilabad', cities: ['Adilabad'] },
      { name: 'Bhadradri Kothagudem', cities: ['Kothagudem'] },
      { name: 'Hanamkonda', cities: ['Hanamkonda'] },
      { name: 'Hyderabad', cities: ['Hyderabad', 'Secunderabad', 'Banjara Hills', 'Hitech City'] },
      { name: 'Jagtial', cities: ['Jagtial'] },
      { name: 'Jangaon', cities: ['Jangaon'] },
      { name: 'Jayashankar Bhupalpally', cities: ['Bhupalpally'] },
      { name: 'Jogulamba Gadwal', cities: ['Gadwal'] },
      { name: 'Kamareddy', cities: ['Kamareddy'] },
      { name: 'Karimnagar', cities: ['Karimnagar'] },
      { name: 'Khammam', cities: ['Khammam'] },
      { name: 'Kumuram Bheem Asifabad', cities: ['Asifabad'] },
      { name: 'Mahabubabad', cities: ['Mahabubabad'] },
      { name: 'Mahabubnagar', cities: ['Mahabubnagar'] },
      { name: 'Mancherial', cities: ['Mancherial'] },
      { name: 'Medak', cities: ['Medak'] },
      { name: 'Medchal-Malkajgiri', cities: ['Kukatpally', 'Malkajgiri'] },
      { name: 'Mulugu', cities: ['Mulugu'] },
      { name: 'Nagarkurnool', cities: ['Nagarkurnool'] },
      { name: 'Nalgonda', cities: ['Nalgonda'] },
      { name: 'Narayanpet', cities: ['Narayanpet'] },
      { name: 'Nirmal', cities: ['Nirmal'] },
      { name: 'Nizamabad', cities: ['Nizamabad', 'Armoor'] },
      { name: 'Peddapalli', cities: ['Peddapalli'] },
      { name: 'Rajanna Sircilla', cities: ['Sircilla'] },
      { name: 'Rangareddy', cities: ['Cyberabad', 'Gachibowli'] },
      { name: 'Sangareddy', cities: ['Sangareddy'] },
      { name: 'Siddipet', cities: ['Siddipet'] },
      { name: 'Suryapet', cities: ['Suryapet'] },
      { name: 'Vikarabad', cities: ['Vikarabad'] },
      { name: 'Wanaparthy', cities: ['Wanaparthy'] },
      { name: 'Warangal', cities: ['Warangal'] },
      { name: 'Yadadri Bhuvanagiri', cities: ['Bhongir'] },
    ],
  },

  // 25. Tripura (8 districts)
  {
    name: 'Tripura',
    languages: ['Bengali', 'Kokborok', 'English', 'Hindi'],
    districts: [
      { name: 'Dhalai', cities: ['Ambassa'] },
      { name: 'Gomati', cities: ['Udaipur'] },
      { name: 'Khowai', cities: ['Khowai'] },
      { name: 'North Tripura', cities: ['Dharmanagar'] },
      { name: 'Sepahijala', cities: ['Bishramganj'] },
      { name: 'South Tripura', cities: ['Belonia'] },
      { name: 'Unakoti', cities: ['Kailashahar'] },
      { name: 'West Tripura', cities: ['Agartala', 'Jirania'] },
    ],
  },

  // 26. Uttar Pradesh (75 districts - COMPLETE OFFICIAL LIST)
  {
    name: 'Uttar Pradesh',
    languages: ['Hindi', 'English', 'Urdu'],
    districts: [
      { name: 'Agra', cities: ['Agra', 'Fatehpur Sikri'] },
      { name: 'Aligarh', cities: ['Aligarh'] },
      { name: 'Ambedkar Nagar', cities: ['Akbarpur'] },
      { name: 'Amethi', cities: ['Amethi', 'Gauriganj'] },
      { name: 'Amroha', cities: ['Amroha'] },
      { name: 'Auraiya', cities: ['Auraiya'] },
      { name: 'Ayodhya', cities: ['Ayodhya', 'Faizabad'] },
      { name: 'Azamgarh', cities: ['Azamgarh'] },
      { name: 'Baghpat', cities: ['Baghpat'] },
      { name: 'Bahraich', cities: ['Bahraich'] },
      { name: 'Ballia', cities: ['Ballia'] },
      { name: 'Balrampur', cities: ['Balrampur'] },
      { name: 'Banda', cities: ['Banda'] },
      { name: 'Barabanki', cities: ['Barabanki'] },
      { name: 'Bareilly', cities: ['Bareilly'] },
      { name: 'Basti', cities: ['Basti'] },
      { name: 'Bhadohi', cities: ['Bhadohi'] },
      { name: 'Bijnor', cities: ['Bijnor'] },
      { name: 'Budaun', cities: ['Budaun'] },
      { name: 'Bulandshahr', cities: ['Bulandshahr'] },
      { name: 'Chandauli', cities: ['Chandauli'] },
      { name: 'Chitrakoot', cities: ['Chitrakoot'] },
      { name: 'Deoria', cities: ['Deoria'] },
      { name: 'Etah', cities: ['Etah'] },
      { name: 'Etawah', cities: ['Etawah'] },
      { name: 'Farrukhabad', cities: ['Farrukhabad'] },
      { name: 'Fatehpur', cities: ['Fatehpur'] },
      { name: 'Firozabad', cities: ['Firozabad'] },
      { name: 'Gautam Buddha Nagar', cities: ['Noida', 'Greater Noida'] },
      { name: 'Ghaziabad', cities: ['Ghaziabad', 'Modinagar'] },
      { name: 'Ghazipur', cities: ['Ghazipur'] },
      { name: 'Gonda', cities: ['Gonda'] },
      { name: 'Gorakhpur', cities: ['Gorakhpur'] },
      { name: 'Hamirpur', cities: ['Hamirpur'] },
      { name: 'Hapur', cities: ['Hapur'] },
      { name: 'Hardoi', cities: ['Hardoi'] },
      { name: 'Hathras', cities: ['Hathras'] },
      { name: 'Jalaun', cities: ['Orai'] },
      { name: 'Jaunpur', cities: ['Jaunpur'] },
      { name: 'Jhansi', cities: ['Jhansi'] },
      { name: 'Kannauj', cities: ['Kannauj'] },
      { name: 'Kanpur Dehat', cities: ['Akbarpur'] },
      { name: 'Kanpur Nagar', cities: ['Kanpur', 'Bithoor'] },
      { name: 'Kasganj', cities: ['Kasganj'] },
      { name: 'Kaushambi', cities: ['Manjhanpur'] },
      { name: 'Kheri', cities: ['Lakhimpur'] },
      { name: 'Kushinagar', cities: ['Padrauna'] },
      { name: 'Lalitpur', cities: ['Lalitpur'] },
      { name: 'Lucknow', cities: ['Lucknow', 'Malihabad'] },
      { name: 'Maharajganj', cities: ['Maharajganj'] },
      { name: 'Mahoba', cities: ['Mahoba'] },
      { name: 'Mainpuri', cities: ['Mainpuri'] },
      { name: 'Mathura', cities: ['Mathura', 'Vrindavan'] },
      { name: 'Mau', cities: ['Mau'] },
      { name: 'Meerut', cities: ['Meerut'] },
      { name: 'Mirzapur', cities: ['Mirzapur'] },
      { name: 'Moradabad', cities: ['Moradabad'] },
      { name: 'Muzaffarnagar', cities: ['Muzaffarnagar'] },
      { name: 'Pilibhit', cities: ['Pilibhit'] },
      { name: 'Pratapgarh', cities: ['Pratapgarh'] },
      { name: 'Prayagraj', cities: ['Prayagraj (Allahabad)'] },
      { name: 'Raebareli', cities: ['Raebareli'] },
      { name: 'Rampur', cities: ['Rampur'] },
      { name: 'Saharanpur', cities: ['Saharanpur'] },
      { name: 'Sambhal', cities: ['Sambhal'] },
      { name: 'Sant Kabir Nagar', cities: ['Khalilabad'] },
      { name: 'Shahjahanpur', cities: ['Shahjahanpur'] },
      { name: 'Shamli', cities: ['Shamli'] },
      { name: 'Shravasti', cities: ['Bhinga'] },
      { name: 'Siddharthnagar', cities: ['Naugarh'] },
      { name: 'Sitapur', cities: ['Sitapur'] },
      { name: 'Sonbhadra', cities: ['Robertsganj'] },
      { name: 'Sultanpur', cities: ['Sultanpur'] },
      { name: 'Unnao', cities: ['Unnao'] },
      { name: 'Varanasi', cities: ['Varanasi', 'Kashi'] },
    ],
  },

  // 27. Uttarakhand (13 districts)
  {
    name: 'Uttarakhand',
    languages: ['Hindi', 'English', 'Garhwali'],
    districts: [
      { name: 'Almora', cities: ['Almora'] },
      { name: 'Bageshwar', cities: ['Bageshwar'] },
      { name: 'Chamoli', cities: ['Gopeshwar'] },
      { name: 'Champawat', cities: ['Champawat'] },
      { name: 'Dehradun', cities: ['Dehradun', 'Rishikesh', 'Mussoorie'] },
      { name: 'Haridwar', cities: ['Haridwar', 'Roorkee'] },
      { name: 'Nainital', cities: ['Nainital', 'Haldwani'] },
      { name: 'Pauri Garhwal', cities: ['Pauri', 'Kotdwar'] },
      { name: 'Pithoragarh', cities: ['Pithoragarh'] },
      { name: 'Rudraprayag', cities: ['Rudraprayag'] },
      { name: 'Tehri Garhwal', cities: ['New Tehri'] },
      { name: 'Udham Singh Nagar', cities: ['Rudrapur', 'Kashipur'] },
      { name: 'Uttarkashi', cities: ['Uttarkashi'] },
    ],
  },

  // 28. West Bengal (23 districts)
  {
    name: 'West Bengal',
    languages: ['Bengali', 'English', 'Hindi'],
    districts: [
      { name: 'Alipurduar', cities: ['Alipurduar'] },
      { name: 'Bankura', cities: ['Bankura'] },
      { name: 'Birbhum', cities: ['Suri', 'Bolpur'] },
      { name: 'Cooch Behar', cities: ['Cooch Behar'] },
      { name: 'Dakshin Dinajpur', cities: ['Balurghat'] },
      { name: 'Darjeeling', cities: ['Darjeeling', 'Siliguri'] },
      { name: 'Hooghly', cities: ['Chinsurah', 'Chandan Nagar'] },
      { name: 'Howrah', cities: ['Howrah', 'Bally'] },
      { name: 'Jalpaiguri', cities: ['Jalpaiguri'] },
      { name: 'Jhargram', cities: ['Jhargram'] },
      { name: 'Kalimpong', cities: ['Kalimpong'] },
      { name: 'Kolkata', cities: ['Kolkata', 'Salt Lake', 'New Town', 'Bhowanipore'] },
      { name: 'Malda', cities: ['English Bazar'] },
      { name: 'Murshidabad', cities: ['Baharampur'] },
      { name: 'Nadia', cities: ['Krishnanagar', 'Kalyani'] },
      { name: 'North 24 Parganas', cities: ['Rajarhat', 'Barasat', 'Barrackpore'] },
      { name: 'Paschim Bardhaman', cities: ['Asansol', 'Durgapur'] },
      { name: 'Paschim Medinipur', cities: ['Midnapore', 'Kharagpur'] },
      { name: 'Purba Bardhaman', cities: ['Bardhaman'] },
      { name: 'Purba Medinipur', cities: ['Tamluk', 'Haldia'] },
      { name: 'Purulia', cities: ['Purulia'] },
      { name: 'South 24 Parganas', cities: ['Alipore', 'Baruipur'] },
      { name: 'Uttar Dinajpur', cities: ['Raiganj'] },
    ],
  },

  // 29-36 UNION TERRITORIES (8)
  {
    name: 'Andaman and Nicobar Islands',
    isUT: true,
    languages: ['Hindi', 'English', 'Bengali', 'Tamil', 'Telugu'],
    districts: [
      { name: 'Nicobar', cities: ['Car Nicobar'] },
      { name: 'North and Middle Andaman', cities: ['Mayabunder'] },
      { name: 'South Andaman', cities: ['Port Blair', 'Garacharma'] },
    ],
  },
  {
    name: 'Chandigarh',
    isUT: true,
    languages: ['Hindi', 'Punjabi', 'English'],
    districts: [
      { name: 'Chandigarh', cities: ['Chandigarh', 'Manimajra'] },
    ],
  },
  {
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    isUT: true,
    languages: ['Gujarati', 'Hindi', 'English', 'Marathi'],
    districts: [
      { name: 'Dadra and Nagar Haveli', cities: ['Silvassa'] },
      { name: 'Daman', cities: ['Daman'] },
      { name: 'Diu', cities: ['Diu'] },
    ],
  },
  {
    name: 'Delhi',
    isUT: true,
    languages: ['Hindi', 'English', 'Punjabi', 'Urdu'],
    districts: [
      { name: 'Central Delhi', cities: ['Karol Bagh', 'Daryaganj'] },
      { name: 'East Delhi', cities: ['Preet Vihar', 'Mayur Vihar'] },
      { name: 'New Delhi', cities: ['Connaught Place', 'Chanakyapuri'] },
      { name: 'North Delhi', cities: ['Civil Lines', 'Pitampura'] },
      { name: 'North East Delhi', cities: ['Shahdara', 'Seelampur'] },
      { name: 'North West Delhi', cities: ['Rohini'] },
      { name: 'Shahdara', cities: ['Shahdara'] },
      { name: 'South Delhi', cities: ['Saket', 'Hauz Khas', 'Vasant Kunj'] },
      { name: 'South East Delhi', cities: ['Lajpat Nagar', 'Okhla'] },
      { name: 'South West Delhi', cities: ['Dwarka'] },
      { name: 'West Delhi', cities: ['Janakpuri', 'Rajouri Garden'] },
    ],
  },
  {
    name: 'Jammu and Kashmir',
    isUT: true,
    languages: ['Urdu', 'Kashmiri', 'Dogri', 'Hindi', 'English'],
    districts: [
      { name: 'Anantnag', cities: ['Anantnag', 'Pahalgam'] },
      { name: 'Bandipora', cities: ['Bandipora'] },
      { name: 'Baramulla', cities: ['Baramulla', 'Gulmarg'] },
      { name: 'Budgam', cities: ['Budgam'] },
      { name: 'Doda', cities: ['Doda'] },
      { name: 'Ganderbal', cities: ['Ganderbal'] },
      { name: 'Jammu', cities: ['Jammu', 'Gandhi Nagar'] },
      { name: 'Kathua', cities: ['Kathua'] },
      { name: 'Kishtwar', cities: ['Kishtwar'] },
      { name: 'Kulgam', cities: ['Kulgam'] },
      { name: 'Kupwara', cities: ['Kupwara'] },
      { name: 'Poonch', cities: ['Poonch'] },
      { name: 'Pulwama', cities: ['Pulwama'] },
      { name: 'Rajouri', cities: ['Rajouri'] },
      { name: 'Ramban', cities: ['Ramban'] },
      { name: 'Reasi', cities: ['Reasi', 'Katras'] },
      { name: 'Samba', cities: ['Samba'] },
      { name: 'Shopian', cities: ['Shopian'] },
      { name: 'Srinagar', cities: ['Srinagar', 'Hazratbal'] },
      { name: 'Udhampur', cities: ['Udhampur'] },
    ],
  },
  {
    name: 'Ladakh',
    isUT: true,
    languages: ['Ladakhi', 'Bhoti', 'Hindi', 'English'],
    districts: [
      { name: 'Kargil', cities: ['Kargil', 'Drass'] },
      { name: 'Leh', cities: ['Leh', 'Shey'] },
    ],
  },
  {
    name: 'Lakshadweep',
    isUT: true,
    languages: ['Malayalam', 'English', 'Hindi'],
    districts: [
      { name: 'Lakshadweep', cities: ['Kavaratti', 'Agatti', 'Minicoy'] },
    ],
  },
  {
    name: 'Puducherry',
    isUT: true,
    languages: ['Tamil', 'English', 'Malayalam', 'Telugu', 'French'],
    districts: [
      { name: 'Karaikal', cities: ['Karaikal'] },
      { name: 'Mahe', cities: ['Mahe'] },
      { name: 'Puducherry', cities: ['Puducherry', 'Oulgaret'] },
      { name: 'Yanam', cities: ['Yanam'] },
    ],
  },
];

export function getAllStatesAndUTs(): string[] {
  return INDIAN_LOCATIONS.map((loc) => loc.name);
}

export function getDistrictsForState(stateName: string): string[] {
  if (!stateName || stateName === 'ALL') return [];
  const state = INDIAN_LOCATIONS.find(
    (s) => s.name.toLowerCase() === stateName.toLowerCase()
  );
  if (!state) return [];
  return state.districts.map((d) => d.name);
}

export function getCitiesForStateAndDistrict(stateName: string, districtName: string): string[] {
  if (!stateName || stateName === 'ALL' || !districtName || districtName === 'ALL') return [];
  const state = INDIAN_LOCATIONS.find(
    (s) => s.name.toLowerCase() === stateName.toLowerCase()
  );
  if (!state) return [];
  const district = state.districts.find(
    (d) => d.name.toLowerCase() === districtName.toLowerCase()
  );
  if (!district) return [];
  return district.cities;
}

export function getLanguagesForState(stateName: string): string[] {
  const state = INDIAN_LOCATIONS.find(
    (s) => s.name.toLowerCase() === stateName.toLowerCase()
  );
  return state ? state.languages : ['English', 'Hindi'];
}

export function getAllAvailableLanguages(): string[] {
  const set = new Set<string>();
  INDIAN_LOCATIONS.forEach((loc) => {
    loc.languages.forEach((lang) => set.add(lang));
  });
  return Array.from(set).sort();
}
